enum MessageTypes {
    USER_JOIN,
    USER_LEAVE,
    CONNECT,
    PING,
    PONG,
    GET_TRACK_SEEK,
    GET_TRACK,
    NEW_TRACK,
    SEEK_TRACK,
    START_TRACK,
    PAUSE_TRACK,
    JOIN_ROOM,
    LEAVE_ROOM,
    CREATE_ROOM,
    RADIO_NEW_TRACK,
    RADIO_GET_TRACK_SEEK,
    RADIO_JOIN_ROOM,
    RADIO_LEAVE_ROOM
}

export default MessageTypes;